title: DyNet
description: The Dynamic Neural Network Toolkit
copyright: © 2017 DyNet
markdown: kramdown
permalink: /news/:year/:month/:day/:title
header_pages:
  - pages/about.md
  - news/index.html
  - pages/docs.md
  - pages/github.md
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-sitemap
paginate: 5
paginate_path: "/news/page:num/"
google_analytics: UA-39940420-2
defaults:
  - scope:
      path: ""
    values:
      image: /assets/logomark.png
