title: DyNet
description: The Dynamic Neural Network Toolkit
copyright: © 2017 DyNet
markdown: kramdown
permalink: /news/:year/:month/:day/:title
header_pages:
  - pages/about.md
  - news/index.html
  - pages/support.md
  - pages/docs.md
  - pages/github.md
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  # - jekyll-sitemap # broken until 3.5.1
paginate: 5
paginate_path: "/news/page:num/"
# google_analytics: UA-XXXXXXXX-1
