title: DyNet
description: The Dynamic Neural Network Toolkit
markdown: kramdown
permalink: /news/:year/:month/:day/:title
header_pages:
  - about.md
  - news/index.html
  - docs.md
  - support.md
  - github.md
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  # - jekyll-sitemap # broken until 3.5.1
paginate: 5
paginate_path: "/news/page:num/"
# google_analytics: UA-XXXXXXXX-1
