title: DyNet
description: The Dynamic Neural Network Toolkit
copyright: © 2017 DyNet
markdown: kramdown
permalink: /news/:year/:month/:day/:title
header_pages:
  - pages/getstarted.md
  - pages/about.md
  - pages/news.md
  - pages/docs.md
  - pages/github.md
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-sitemap
paginate: 5
google_analytics: UA-39940420-2
defaults:
  - scope:
      path: ""
    values:
      image: /assets/logomark.png
  - scope:
      path: "_posts"
    values:
      redirect_to:
        - /#news
